# Generated by Django 5.1.1 on 2024-09-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=50)),
                ('ad_server', models.CharField(help_text='Example: ldaps://dc1.example.ru:636', max_length=50)),
                ('base_dn', models.CharField(help_text='Example: OU=test,OU=users,DC=example,DC=ru', max_length=500)),
                ('retrieve_attributes', models.CharField(default='mobile,givenName', help_text='with separator ",", but whitout spaces', max_length=500)),
                ('search_filter', models.CharField(help_text='Example: (&(sAMAccountName={})(objectCategory=person)(objectClass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(mail=*@example.ru)(mobile=+7*)(!(memberOf:1.2.840.113556.1.4.1941:=CN=Domain Admins,CN=Users,DC=example,DC=ru)))', max_length=500)),
                ('admin_username', models.CharField(max_length=50)),
                ('admin_password', models.CharField(max_length=50)),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
    ]
