# Generated by Django 5.1.1 on 2024-09-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resetme', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='domain_choise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[], max_length=15, verbose_name='Выберите домен из списка:')),
            ],
        ),
    ]
